# Generated by Django 5.1.2 on 2024-10-28 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0002_rename_user_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='character',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.character'),
        ),
    ]
