# Generated by Django 5.1.2 on 2024-11-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
