# Generated by Django 5.1.2 on 2024-11-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0007_remove_character_room_alter_character_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='skin',
            field=models.ImageField(default='skins/default_image.jpg', upload_to='skins/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='perms',
            field=models.BooleanField(default=False),
        ),
    ]
