# Generated by Django 5.1.2 on 2024-11-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0010_character_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='answer',
            field=models.CharField(default='', max_length=50),
        ),
    ]
