# Generated by Django 5.1.2 on 2024-11-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0011_room_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='avatar',
            field=models.ImageField(default='skins/default_image.jpg', upload_to='skins/'),
        ),
    ]
