# Generated by Django 5.1.2 on 2024-11-16 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0012_character_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
