# Generated by Django 5.1.2 on 2024-11-29 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0016_alter_player_current_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='answers_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='interface.room'),
        ),
    ]
